// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoChallengeMottu.Data;

#nullable disable

namespace ProjetoChallengeMottu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoChallengeMottu.Models.EchoBeacon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("MotoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NumeroIdentificacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("Id");

                    b.HasIndex("MotoId")
                        .IsUnique()
                        .HasFilter("\"MotoId\" IS NOT NULL");

                    b.ToTable("ECHOBEACON");
                });

            modelBuilder.Entity("ProjetoChallengeMottu.Models.Moto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("Id");

                    b.ToTable("MOTOS");
                });

            modelBuilder.Entity("ProjetoChallengeMottu.Models.EchoBeacon", b =>
                {
                    b.HasOne("ProjetoChallengeMottu.Models.Moto", "Moto")
                        .WithOne("EchoBeacon")
                        .HasForeignKey("ProjetoChallengeMottu.Models.EchoBeacon", "MotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("ProjetoChallengeMottu.Models.Moto", b =>
                {
                    b.Navigation("EchoBeacon");
                });
#pragma warning restore 612, 618
        }
    }
}
